version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    container_name: fool_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.prod

  web:
    build: .
    env_file:
      - .env.prod
    container_name: fool
    command: ["/app/docker/app.sh"]
    volumes:
      - ./media:/app/media
    ports:
      - "9000:8000"
    depends_on:
      - db

volumes:
  postgres_data: